---
- name: core apt packages
  apt:
     name={{item}}
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common
- name: apt key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    id: 0EBFCD88
- name: docker apt repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
  register: docker_apt_repo
- command: apt-get update
  when: docker_apt_repo.changed
- name: docker
  apt: 
    name: docker-ce
