---
- name: core apt packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    update_cache: yes
- name: apt key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    id: 0EBFCD88
- name: docker apt repo
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
- name: docker
  apt: 
    name: docker-ce
    update_cache: yes
- name: docker config with journald driver
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
         "log-driver": "journald"
      }
  register: docker_default_config
- service:
    name: docker
    state: restarted
  when: docker_default_config.changed

